#!/usr/bin/env bash

IN_NAME=$1     # Name for key file to idetify it. E.g. "github" will generate files "id_ed25519.github" and "id_ed25519.github.pub"
IN_HOST=$2     # SSH host. E.g. "github.com"
IN_KEY_TYPE=$3 # Type of key. Optional. Default value is ed25519

KEY_TYPE="ed25519"

if [[ -n "$IN_KEY_TYPE" ]]; then
    KEY_TYPE=$IN_KEY_TYPE
fi

FILE_NAME="id_$KEY_TYPE"
PATH_TO_KEY="$HOME/.ssh/$FILE_NAME.$IN_NAME"
PATH_TO_PUB_KEY="$PATH_TO_KEY.pub"

ssh-keygen -t $KEY_TYPE -f "$PATH_TO_KEY" -N ""

# Copy key to clipboard
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Works for X Window System, doesn't work for Wayland
    cat $PATH_TO_PUB_KEY | xclip -sel clip
    echo "Public key copied to clipboard"
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # If MacOS X
    cat $PATH_TO_PUB_KEY | pbcopy
    echo "Public key copied to clipboard"
else
    echo "Generated public key:"
    cat $PATH_TO_PUB_KEY
fi

# Add record to config file (create if not exists)
CONFIG_FILE="$HOME/.ssh/config"

echo "Host $IN_HOST" >> $CONFIG_FILE
echo "    Hostname $IN_HOST" >> $CONFIG_FILE
echo "    IdentityFile $PATH_TO_KEY" >> $CONFIG_FILE
echo "    IdentitiesOnly yes" >> $CONFIG_FILE
echo "    AddKeysToAgent yes" >> $CONFIG_FILE
echo "    PreferredAuthentications publickey" >> $CONFIG_FILE
